/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Exchange first name + startcode for a permanent access key
         * @description Verifies the startcode for a user, generates a UUID access_key, stores it hashed (bcrypt), and returns the plaintext key. The access_key is shown only in this response — save it. Calling this endpoint a second time for an already-activated user is rejected with 400.
         */
        post: operations["activate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign in with an access key, returning the user profile
         * @description Validates the access_key (bcrypt-checked against the stored hash) and returns the user profile. Used by the frontend on the sign-in form. After a successful login, the client should send the access_key in the `X-Access-Key` header on all subsequent requests.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/identity-tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Issue a short-lived identity token for amusement redirects
         * @description Generates a 30-minute identity token bound to the authenticated user. The token is multi-use during its TTL — each call to `POST /transactions` accepts the same token — but it can mint at most one stamp.
         *     The token is intended to be passed as a `?identity_token=<token>` query parameter when redirecting the user to an amusement. The amusement then uses the token in a `POST /transactions` body to identify the user without exposing their long-lived access key.
         *     The amusement should immediately strip the parameter from the URL (e.g. via `history.replaceState`) so it doesn't leak via referer headers, browser history, or server logs.
         */
        post: operations["issueIdentityToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/identity-tokens/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Resolve an identity token to its user (without consuming it)
         * @description Used by an amusement after the user lands on its page. The amusement reads the `identity_token` from the URL and calls this endpoint to get back minimal user info (id and name) so it can greet the rider before charging. The token is **not** consumed — only `POST /transactions` consumes it.
         *     Unauthenticated: possession of a valid (unexpired, unconsumed) token is sufficient.
         */
        get: operations["resolveIdentityToken"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current user profile */
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update profile information */
        patch: operations["updateCurrentUser"];
        trace?: never;
    };
    "/groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all groups */
        get: operations["listGroups"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Single group with members and amusements
         * @description If the requesting user belongs to this group, each amusement includes its `api_key`. Non-members receive amusements without `api_key`.
         */
        get: operations["getGroup"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Rename a group
         * @description Any member of the group can rename it. The `name` must be 1–50 characters and unique across all groups (case-insensitive comparison). A 422 is returned if the name is already taken.
         */
        patch: operations["updateGroup"];
        trace?: never;
    };
    "/amusements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all amusements
         * @description Returns all registered amusements. `api_key` is never included in this public listing.
         */
        get: operations["listAmusements"];
        put?: never;
        /**
         * Register a new amusement
         * @description The amusement is automatically linked to the requesting user's group. `name` must be globally unique across all amusements; a duplicate returns 422. Returns the `api_key` — save it, it is only shown once in this response. To retrieve the key later, use `GET /groups/{id}` (group members only).
         */
        post: operations["createAmusement"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/amusements/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Single amusement detail
         * @description If the requesting user belongs to the amusement's group, the response includes `api_key`. Otherwise it is omitted.
         */
        get: operations["getAmusement"];
        put?: never;
        post?: never;
        /**
         * Delete an amusement
         * @description Any member of the amusement's group can delete it. Deletion is blocked if the amusement has a non-zero balance — settle first.
         */
        delete: operations["deleteAmusement"];
        options?: never;
        head?: never;
        /**
         * Update an amusement
         * @description Any member of the amusement's group can update it. `name` must stay globally unique; a duplicate (other than this amusement's current name) returns 422.
         */
        patch: operations["updateAmusement"];
        trace?: never;
    };
    "/amusements/{id}/regenerate-key": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rotate the amusement's API key
         * @description Invalidates the old key and returns a new one. Any member of the amusement's group can do this.
         */
        post: operations["regenerateAmusementKey"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/amusements/{id}/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all fees and payouts for an amusement
         * @description Returns every transaction (fees in + payouts out) for an amusement, newest first. Only members of the amusement's group can access it. Useful for live monitoring during the event.
         */
        get: operations["listAmusementTransactions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/amusements/{id}/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Aggregated P&L stats for an amusement
         * @description Returns the live balance plus total fees in, total payouts out, and net for an amusement. Group members only.
         */
        get: operations["getAmusementStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Deduct money from a user and award a stamp
         * @description Used when a user plays a game or visits an attraction. The amusement's balance is credited. A random stamp is generated and returned.
         *     The returned `transaction_id` is required for `POST /transactions/{id}/payout` if the user wins.
         */
        post: operations["createTransaction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transactions/{id}/payout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Pay winnings to a user from the amusement's balance
         * @description Called after the user wins a game. Deducts from the amusement's balance and credits the user. The transaction is marked as settled — double payout is rejected.
         *     Payouts always succeed regardless of the amusement's balance: `amusement_balance` can go negative and is reconciled at `POST /settle` (group members absorb any debt). This makes player payouts UX-bulletproof.
         *     The `api_key` in the body must belong to the same amusement that created the original transaction. Attractions (`type: attraction`) are rejected — only games can pay out.
         */
        post: operations["payoutTransaction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stamps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get current user's unexchanged stamps with total VP
         * @description Returns the user's unexchanged stamps along with their total Victory Points (VP). VP is computed server-side using the same partition algorithm described under `GET /leaderboard`, so the value matches what will appear on the final leaderboard.
         *     **VP penalty:** if any amusement in the user's group has `amusement_balance < 0`, `total_vp` is returned as 0 regardless of stamp holdings. This is the same rule applied by `GET /leaderboard`.
         */
        get: operations["listStamps"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/exchanges": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Exchange stamp sets for money
         * @description Submit stamp IDs. The server forms sets greedily in this order, picking the highest-value sets first:
         *     1. **Metal sets** (silver + gold + platinum, any animals) — €10 each 2. **Animal sets** (all five animals, any metals) — €7 each 3. **Non-metal sets** (3 distinct animals with no metal) — €3 each
         *     Only stamps that end up in a formed set are consumed; stamps left over stay in the user's collection and remain eligible for Victory Points. This means you can safely submit your entire collection and let the server take only what pays.
         *     Money is created out of thin air — exchanges do not affect any amusement's balance.
         */
        post: operations["exchangeStamps"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/votes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Vote for the nicest amusement
         * @description One vote per user. Voting again replaces your previous vote (upsert). Users are free to vote for amusements in their own group.
         */
        post: operations["castVote"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * End-of-showdown settlement (admin only)
         * @description Called **once** at the end of the showdown by an admin-group member. For each amusement whose `amusement_balance` is negative, the absolute amount is split equally across the amusement's group members and deducted from their personal balances (members may go negative). `amusement_balance` itself is NOT zeroed — it remains negative as a historical record and continues to trigger the VP penalty. `amusements.settled_at` is set, making subsequent calls a no-op for that amusement.
         */
        post: operations["settle"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leaderboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Final leaderboard
         * @description Top 10 in each category.
         *     **Rankings:** - **Richest**: users ordered by personal balance (descending). - **Most VP**: users ordered by Victory Points (descending). - **Nicest amusements**: amusements ordered by vote count (descending).
         *     **VP calculation:** 1. `metal_sets = min(silver_count, gold_count, platinum_count)` →
         *        `40 × metal_sets` VP.
         *     2. `animal_sets = min(count per animal across all five animals)` →
         *        `25 × animal_sets` VP. Computed from the full collection — a
         *        metal stamp counts toward both its metal slot and its animal slot.
         *     3. `loose` = stamps that end up in neither a metal set nor an animal
         *        set, after maximizing the overlap between the two (i.e. when a
         *        metal stamp can serve both a metal slot and an animal slot, it
         *        does). VP awarded as the `loose`-th triangular number
         *        (1 → 1, 2 → 3, 3 → 6, 4 → 10, …).
         *     4. Total VP is the sum of the three.
         *     Example: collection `[lion, dolphin, snake, gold-dolphin, gold-dolphin, platinum-beetlebug, silver-toucan]` (7 stamps). 1 metal set (silver-toucan + 1 gold-dolphin + platinum-beetlebug — with toucan and beetlebug also filling animal-set slots) + 1 animal set + 2 loose dolphins → 40 + 25 + 3 = **68 VP**.
         *     Only unexchanged stamps are counted. Stamps are never deleted by this endpoint — the partition is purely arithmetic.
         *     **VP penalty:** if any amusement in the user's group has `amusement_balance < 0` at the time `/leaderboard` is read, that user's `total_vp` is forced to 0 regardless of stamp holdings. This persists after `/settle` (the tracker is not zeroed).
         *     **Tie-breaking** in all three rankings: lower `id` (or earliest creation) wins.
         */
        get: operations["getLeaderboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        User: {
            /** Format: uuid */
            readonly uuid?: string;
            /** @example Amin */
            first_name?: string;
            /** @example null */
            last_name?: string | null;
            /**
             * Format: uri
             * @example https://github.com/amin
             */
            github_url?: string | null;
            /**
             * Format: uri
             * @example null
             */
            website_url?: string | null;
            /** @example 25 */
            readonly balance?: number;
            readonly group?: components["schemas"]["GroupSummary"];
            /** @example 4 */
            readonly stamp_count?: number;
        };
        UserSummary: {
            /** Format: uuid */
            uuid?: string;
            first_name?: string;
            last_name?: string | null;
            /** Format: uri */
            github_url?: string | null;
            /** Format: uri */
            website_url?: string | null;
        };
        GroupSummary: {
            id?: number;
            /** @example Centralbank */
            name?: string;
            /** @example 3 */
            member_count?: number;
        };
        Group: components["schemas"]["GroupSummary"] & {
            /**
             * @description Sum of all amusement balances belonging to this group.
             * @example 45
             */
            total_balance?: number;
            members?: components["schemas"]["UserSummary"][];
            amusements?: components["schemas"]["Amusement"][];
        };
        Amusement: {
            readonly id?: number;
            /**
             * @description Globally unique across all amusements.
             * @example Fortune Wheel
             */
            name?: string;
            description?: string | null;
            /** @enum {string} */
            type?: "game" | "attraction";
            /**
             * Format: uri
             * @example https://fortune.example.com
             */
            url?: string;
            /**
             * Format: uri
             * @example https://fortune.example.com/banner.png
             */
            image_url?: string | null;
            /**
             * @description Fixed entrance fee / stake. Null = variable amount per transaction.
             * @example 5
             */
            price?: number | null;
            /** @example 20 */
            player_payout?: number | null;
            /**
             * @description Current pooled balance of this amusement.
             * @example 15.5
             */
            readonly amusement_balance?: number;
            /**
             * Format: uuid
             * @description Only included on `POST /amusements` (create response) and for group members via `GET /amusements/{id}` or `GET /groups/{id}`. Never exposed in public listings.
             * @example 0b3c8a4e-7f7a-4b4d-9c9c-2a4a6b6c8d8e
             */
            api_key?: string;
            readonly group_id?: number;
            /** Format: date-time */
            readonly created_at?: string;
        };
        TransactionListItem: {
            readonly id?: number;
            readonly user_id?: number;
            /** @example 5 */
            amount?: number;
            /** @enum {string} */
            type?: "fee" | "payout" | "owner_revenue" | "exchange";
            /** Format: date-time */
            readonly created_at?: string;
        };
        AmusementStats: {
            /**
             * @description Current pooled balance. Can be negative (debt).
             * @example -15.5
             */
            amusement_balance?: number;
            /**
             * @description Sum of all fee transactions.
             * @example 50
             */
            fees_total?: number;
            /** @example 10 */
            fees_count?: number;
            /**
             * @description Sum of all payout transactions.
             * @example 65.5
             */
            payouts_total?: number;
            /** @example 3 */
            payouts_count?: number;
            /**
             * @description fees_total minus payouts_total.
             * @example -15.5
             */
            net?: number;
        };
        Stamp: {
            readonly id?: number;
            /** @description ID of the transaction that minted this stamp. */
            readonly transaction_id?: number | null;
            /**
             * @example dolphin
             * @enum {string}
             */
            animal?: "lion" | "dolphin" | "toucan" | "beetlebug" | "snake";
            /**
             * @example gold
             * @enum {string|null}
             */
            metal?: "silver" | "gold" | "platinum" | null;
            /**
             * Format: uri
             * @description Absolute URL to the stamp's SVG image.
             * @example https://api.example.com/images/stamps/gold-dolphin.svg
             */
            readonly image_url?: string;
            /** Format: date-time */
            readonly created_at?: string;
        };
        TransactionResponse: {
            /** @description Transaction ID. Save this — it is required for payout. */
            transaction_id?: number;
            /**
             * @description Amount deducted from the user's balance, echoed back.
             * @example 1.95
             */
            amount?: number;
            /** @description Newly minted stamp, or null if this identity_token has already had its single stamp-issuing attempt, or if a stamped transaction for this (user, amusement) pair exists within the last 3 minutes (anti-farming guard). */
            stamp?: {
                /**
                 * @example dolphin
                 * @enum {string}
                 */
                animal?: "lion" | "dolphin" | "toucan" | "beetlebug" | "snake";
                /**
                 * @example gold
                 * @enum {string|null}
                 */
                metal?: "silver" | "gold" | "platinum" | null;
                /**
                 * Format: uri
                 * @example https://api.example.com/images/stamps/gold-dolphin.svg
                 */
                image_url?: string;
            } | null;
        };
        ExchangeResponse: {
            /**
             * @description Total euros received from this exchange.
             * @example 10
             */
            amount?: number;
            sets_exchanged?: {
                /**
                 * @description Number of 3-metal sets found (€10 each).
                 * @example 1
                 */
                metal_sets?: number;
                /**
                 * @description Number of 5-animal sets found (€7 each).
                 * @example 0
                 */
                animal_sets?: number;
                /**
                 * @description Number of 3-distinct-non-metal-animal sets found (€3 each).
                 * @example 0
                 */
                non_metal_sets?: number;
            };
            /**
             * @description Count of submitted stamps that were used by the greedy set formation. Stamps not used are left in the user's collection.
             * @example 3
             */
            stamps_consumed?: number;
        };
        SettlementResponse: {
            /**
             * @description Number of amusements processed in this call.
             * @example 12
             */
            amusements_settled?: number;
            details?: {
                amusement_id?: number;
                amusement_name?: string;
                /** @description Balance at settlement time (positive = profit, negative = deficit). Not zeroed. */
                amusement_balance?: number;
                /** @description Per-member deduction applied at settle. Equals `floor(sum_payouts / member_count)` — i.e., each member pays their share of the money the system created via payouts. 0 if no payouts occurred or the amusement has no members. */
                deducted_per_member?: number;
                member_count?: number;
            }[];
        };
        Leaderboard: {
            richest?: {
                user?: components["schemas"]["UserSummary"];
                balance?: number;
            }[];
            most_vp?: {
                user?: components["schemas"]["UserSummary"];
                /** @description Total Victory Points */
                vp?: number;
            }[];
            nicest_amusements?: {
                amusement?: components["schemas"]["Amusement"];
                votes?: number;
            }[];
        };
        Error: {
            message?: string;
        };
    };
    responses: {
        /** @description Missing or invalid credentials */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The authenticated user is not a member of the required group. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Validation failed */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @example The name field is required. */
                    message?: string;
                    errors?: {
                        [key: string]: string[];
                    };
                };
            };
        };
    };
    parameters: {
        GroupId: number;
        AmusementId: number;
        /** @description ID of the original transaction (from `POST /transactions`). */
        TransactionId: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    activate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @example Amin */
                    first_name: string;
                    /**
                     * Format: uuid
                     * @example 9f1c2a14-7e5e-4a8a-b5b1-19d2a3a5f201
                     */
                    startcode: string;
                };
            };
        };
        responses: {
            /** @description Activation successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Activation successful */
                        message?: string;
                        /**
                         * @description Plaintext access key. Stored hashed server-side.
                         * @example 8d1f1c8a-12d4-4f3a-9b9b-77d9b66e30e1
                         */
                        access_key?: string;
                    };
                };
            };
            /** @description User already activated */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Invalid startcode */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @example 8d1f1c8a-12d4-4f3a-9b9b-77d9b66e30e1 */
                    access_key: string;
                };
            };
        };
        responses: {
            /** @description Login successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    issueIdentityToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Identity token issued */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * Format: uuid
                         * @example 0b3c8a4e-7f7a-4b4d-9c9c-2a4a6b6c8d8e
                         */
                        identity_token: string;
                        /**
                         * Format: date-time
                         * @example 2026-05-09T11:25:00+00:00
                         */
                        expires_at: string;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    resolveIdentityToken: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The identity token from the URL query parameter. */
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Token is valid; user attached */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        user: {
                            /** @example 1 */
                            id: number;
                            /** @example Amin */
                            name: string;
                        };
                        /**
                         * Format: date-time
                         * @example 2026-05-09T11:25:00+00:00
                         */
                        expires_at: string;
                    };
                };
            };
            /** @description Token is missing, invalid, expired, or already consumed */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User profile including balance, group, and stamp count */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    updateCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    last_name?: string | null;
                    /**
                     * Format: uri
                     * @example https://github.com/amin
                     */
                    github_url?: string | null;
                    /**
                     * Format: uri
                     * @example https://amin.dev
                     */
                    website_url?: string | null;
                };
            };
        };
        responses: {
            /** @description Updated user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["ValidationError"];
        };
    };
    listGroups: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All groups */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["GroupSummary"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getGroup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["GroupId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Group detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Group"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    updateGroup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["GroupId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @example Centralbank */
                    name: string;
                };
            };
        };
        responses: {
            /** @description Updated group */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Group"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationError"];
        };
    };
    listAmusements: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All registered amusements */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["Amusement"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createAmusement: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * @description Globally unique amusement name.
                     * @example Fortune Wheel
                     */
                    name: string;
                    /** @example Spin the wheel and test your luck */
                    description?: string | null;
                    /** @enum {string} */
                    type: "game" | "attraction";
                    /**
                     * Format: uri
                     * @example https://fortune.example.com
                     */
                    url: string;
                    /**
                     * Format: uri
                     * @example https://fortune.example.com/banner.png
                     */
                    image_url?: string | null;
                    /**
                     * @description Entrance fee / stake. Leave null for variable-stake amusements that pass the amount in each transaction body.
                     * @example 5
                     */
                    price?: number | null;
                    /**
                     * @description Fixed payout amount, if applicable.
                     * @example 20
                     */
                    player_payout?: number | null;
                };
            };
        };
        responses: {
            /** @description Amusement registered. The response always includes `api_key` — save it, it is only shown in this response. To retrieve the key later, use `GET /groups/{id}` (group members only). */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Amusement registered. Save the api_key — it is only shown here. */
                        message: string;
                        amusement: components["schemas"]["Amusement"];
                    };
                };
            };
            /** @description User has no group_id */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["ValidationError"];
        };
    };
    getAmusement: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["AmusementId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Amusement detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Amusement"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteAmusement: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["AmusementId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Amusement deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description Cannot delete amusement with non-zero balance */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    updateAmusement: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["AmusementId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    name?: string;
                    description?: string | null;
                    /** @enum {string} */
                    type?: "game" | "attraction";
                    /** Format: uri */
                    url?: string;
                    /** Format: uri */
                    image_url?: string | null;
                    price?: number | null;
                    player_payout?: number | null;
                };
            };
        };
        responses: {
            /** @description Updated amusement */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Amusement"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationError"];
        };
    };
    regenerateAmusementKey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["AmusementId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description New API key generated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * Format: uuid
                         * @example 0b3c8a4e-7f7a-4b4d-9c9c-2a4a6b6c8d8e
                         */
                        api_key?: string;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listAmusementTransactions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["AmusementId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Transaction list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["TransactionListItem"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    getAmusementStats: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["AmusementId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stats */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AmusementStats"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    createTransaction: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * Format: uuid
                     * @description Identity token from the URL query parameter. Multi-use during its TTL (default 30 min). Each token can mint at most one stamp; subsequent calls with the same token still process payments but return `stamp: null`.
                     */
                    identity_token: string;
                    /**
                     * @description Amount to deduct in euros (2-decimal precision; minimum 0.10). Optional — when omitted, the amusement's stored `price` is used. If `amount` is omitted and the amusement has no `price`, the request is rejected with 422.
                     * @example 1.95
                     */
                    amount?: number;
                    /**
                     * Format: uuid
                     * @description The calling amusement's `api_key`. Identifies and authenticates the amusement. Invalid key returns 401.
                     */
                    api_key: string;
                };
            };
        };
        responses: {
            /** @description Money deducted and stamp awarded */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description User has insufficient funds */
            402: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            404: components["responses"]["NotFound"];
            /** @description The amusement has already been settled and no longer accepts transactions. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    payoutTransaction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID of the original transaction (from `POST /transactions`). */
                id: components["parameters"]["TransactionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * @description Winnings to pay out in euros (2-decimal precision). Optional — when omitted, the amusement's stored `player_payout` is used. If `amount` is omitted and the amusement has no `player_payout`, the request is rejected with 422.
                     * @example 10
                     */
                    amount?: number;
                    /**
                     * Format: uuid
                     * @description The calling amusement's `api_key`. Must match the amusement that owns the original transaction.
                     */
                    api_key: string;
                };
            };
        };
        responses: {
            /** @description Payout completed */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description ID of the newly-created payout transaction. */
                        transaction_id: number;
                        /**
                         * @description Amount credited to the user, echoed back.
                         * @example 10
                         */
                        amount: number;
                    };
                };
            };
            /** @description The referenced transaction is not a `fee` (e.g. a `payout` row). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description API key does not match the transaction's amusement */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            404: components["responses"]["NotFound"];
            /** @description Conflict — either the transaction has already been paid out, or the amusement is an attraction (attractions cannot pay out). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listStamps: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User's stamp collection and total VP */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Stamp"][];
                        /**
                         * @description Sum of Victory Points the user would receive on the leaderboard given their current unexchanged stamps.
                         * @example 65
                         */
                        total_vp: number;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    exchangeStamps: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * @example [
                     *       1,
                     *       2,
                     *       3,
                     *       4,
                     *       5,
                     *       6,
                     *       7
                     *     ]
                     */
                    stamp_ids: number[];
                };
            };
        };
        responses: {
            /** @description Exchange result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExchangeResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Validation failed, or one or more stamp IDs do not belong to the authenticated user. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    castVote: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @example 3 */
                    amusement_id: number;
                };
            };
        };
        responses: {
            /** @description Vote recorded */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Vote recorded */
                        message?: string;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Amusement not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            422: components["responses"]["ValidationError"];
        };
    };
    settle: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Settlement summary */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettlementResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Caller's group is not an admin group */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getLeaderboard: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Leaderboard data */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Leaderboard"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
}
